# nonk8s
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kude-controller
build:
  local:
    push: false
    useBuildkit: true
    concurrency: 0
  artifacts:
  - image: controller
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - config
    buildArgs:
      - --reorder none
    hooks:
      before:
        - host:
            command: [./delete-cluster-resources.sh]
            dir: scripts
      after:
        - host:
            command: [kubectl, apply, -f, "repos.yaml", "bundles.yaml"]
            dir: test
