# nonk8s
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kude-controller
build:
  local:
    push: false
    useBuildkit: true
    concurrency: 0
  artifacts:
  - image: controller
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - config
    buildArgs:
      - --reorder none
    hooks:
      before:
        - host:
            command: [./scripts/delete-cluster-resources.sh]
      after:
        - host:
            command: [./scripts/deploy-test-resources.sh]
