---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kude
    app.kubernetes.io/component: controller
  name: kude-controller
rules:
- apiGroups:
  - vcs.kude.kfirs.com
  resources:
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vcs.kude.kfirs.com
  resources:
  - gitrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - vcs.kude.kfirs.com
  resources:
  - gitrepositories/status
  verbs:
  - get
  - patch
  - update
