---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kude-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kude.kfirs.com
  resources:
  - commandruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kude.kfirs.com
  resources:
  - commandruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kude.kfirs.com
  resources:
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kude.kfirs.com
  resources:
  - gitrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - kude.kfirs.com
  resources:
  - gitrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kude.kfirs.com
  resources:
  - kubectlbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kude.kfirs.com
  resources:
  - kubectlbundles/finalizers
  verbs:
  - update
- apiGroups:
  - kude.kfirs.com
  resources:
  - kubectlbundles/status
  verbs:
  - get
  - patch
  - update
