apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: kude
  labels:
    app.kubernetes.io/name: kude
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kude
      app.kubernetes.io/component: controller
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kude
        app.kubernetes.io/component: controller
    spec:
      containers:
        - image: controller
          args:
            - --zap-log-level=3
          name: controller
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: health
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: controller
