apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: kude
  labels:
    app.kubernetes.io/name: kude
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kude
      app.kubernetes.io/component: controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kude
        app.kubernetes.io/component: controller
    spec:
      containers:
        - command:
            - /controller
          image: controller
          name: controller
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: controller
      terminationGracePeriodSeconds: 30
