name: Build branch
run-name: Build ${{ github.ref }}

on:
  push:
    branches: ['*']

defaults:
  run:
    shell: bash -eu {0}

jobs:

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      version: 0.0.0-dev+${GITHUB_SHA::7}
    secrets: inherit

  build-docker:
    name: Build Docker images
    needs: test
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
