name: Build branch
run-name: Build ${{ github.ref }}

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

defaults:
  run:
    shell: bash -eu {0}

jobs:

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      version: 0.0.0-dev+${{ github.sha }}
    secrets: inherit

  docker:
    name: Docker
    needs: test
    uses: ./.github/workflows/docker.yml
    with:
      version: 0.0.0-dev+${{ github.sha }}
    secrets: inherit
