name: Build branch
run-name: Build branch ${{ github.ref_name }}

on:
  push:
    branches: ['*']

defaults:
  run:
    shell: bash -eu {0}

env:
  VERSION: 0.0.0-dev+${{ github.sha }}.runID${{ github.run_id }}.runNum${{ github.run_number }}.attempt${{ github.run_attempt }}

jobs:

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      version: ${{ env.VERSION }}
    secrets: inherit

  docker:
#    name: Docker
#    needs: test
#    uses: ./.github/workflows/docker.yml
#    with:
#      version: ${{ env.VERSION }}
#    secrets: inherit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-
            buildx-
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build --build-arg 'VERSION=${VERSION}' \
                       --cache-from type=local,src=/tmp/.buildx-cache \
                       --cache-to type=local,mode=max,dest=/tmp/.buildx-cache-new \
                       --file Dockerfile \
                       --push \
                       -tag ghcr.io/arikkfir/kude-controller:${GITHUB_SHA} \
                       .
      - run: |
          docker tag ghcr.io/arikkfir/kude-controller:${GITHUB_SHA} ghcr.io/arikkfir/kude-controller:${GITHUB_SHA::7}
          docker push ghcr.io/arikkfir/kude-controller:${GITHUB_SHA::7}
      - run: |
          docker tag ghcr.io/arikkfir/kude-controller:${GITHUB_SHA} ghcr.io/arikkfir/kude-controller:${{ github.ref_name }} .
          docker push ghcr.io/arikkfir/kude-controller:${{ github.ref_name }}
      - run: rm -rf /tmp/.buildx-cache && mv /tmp/.buildx-cache-new /tmp/.buildx-cache
