name: Build PR
run-name: Build PR#${{ github.ref_name }}

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

env:
  VERSION: 0.0.0-dev+${{ github.sha }}.${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}

defaults:
  run:
    shell: bash -eu {0}

jobs:

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      version: 0.0.0-dev+${{ github.sha }}
    secrets: inherit

#  docker:
#    name: Docker
#    needs: test
#    uses: ./.github/workflows/docker.yml
#    with:
#      version: 0.0.0-dev+${{ github.sha }}
#    secrets: inherit
