name: Build tag
run-name: Build tag ${{ github.ref_name }}

on:
  push:
    tags: ['*']

defaults:
  run:
    shell: bash -eu {0}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod
      - run: go mod download
      - run: go vet ./...
      - run: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
      - run: setup-envtest use 1.25.0 --bin-dir=./bin
      - run: |
          go test \
            -ldflags "-X 'github.com/arikkfir/kude-controller/internal.versionString=${{ github.ref_name }}+${GITHUB_SHA::7}'" \
            -v \
            -vet=off \
            -race \
            -shuffle ${{ github.run_number }} \
            -coverprofile=coverage.txt -covermode=atomic \
            ./...
      - uses: codecov/codecov-action@v3
        if: always()

  docker:
    name: Docker
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-
            buildx-
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build --build-arg 'VERSION=${{ github.ref_name }}+${GITHUB_SHA::7}' \
                       --cache-from=type=local,src=/tmp/.buildx-cache \
                       --cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new \
                       --file Dockerfile \
                       --push \
                       --tag ghcr.io/arikkfir/kude-controller:${GITHUB_SHA} \
                       --tag ghcr.io/arikkfir/kude-controller:${GITHUB_SHA::7} \
                       --tag ghcr.io/arikkfir/kude-controller:${{ github.ref_name }} \
                       .
          rm -rf /tmp/.buildx-cache && mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  helm:
    name: Helm
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: helm package ./chart --app-version=${{ github.ref_name }}+${GITHUB_SHA::7} --destination=. --version=${{ github.ref_name }}+${GITHUB_SHA::7}
      - run: helm push kude-controller-${{ github.ref_name }}+${GITHUB_SHA::7}.tgz oci://ghcr.io/arikkfir
