name: Build PR

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

defaults:
  run:
    shell: bash -eu {0}

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
          restore-keys: |
            golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-
            golang-${{ runner.os }}-
      - run: go mod download
      - run: go vet ./...
      - run: |
          go test -ldflags "-X 'github.com/arikkfir/kude-controller/internal.gitCommit=${GITHUB_SHA}'" \
                  -v \
                  -vet=off \
                  -race \
                  -shuffle ${SHUFFLE_SEED} \
                  -coverprofile=coverage.txt \
                  -covermode=atomic \
                  ./...
        env:
          SHUFFLE_SEED: ${{ github.run_number }}
      - uses: codecov/codecov-action@v3
        if: always()

  build:
    name: Build Image
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-
            buildx-
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/arikkfir/kude-controller
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=,format=short
            type=sha,prefix=,format=long
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
      - uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          file: Dockerfile
          labels: ${{ steps.docker-meta.outputs.labels }}
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
      - run: rm -rf /tmp/.buildx-cache && mv /tmp/.buildx-cache-new /tmp/.buildx-cache
