name: Test

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

defaults:
  run:
    shell: bash -eu {0}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod
      - run: go mod download
      - run: go vet ./...
      - run: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
      - run: setup-envtest use 1.25.0 --bin-dir=./bin
      - run: |
          go test \
            -ldflags "-X 'github.com/arikkfir/kude-controller/internal.versionString=${{ inputs.version }}'" \
            -v \
            -vet=off \
            -race \
            -shuffle ${{ github.run_number }} \
            -coverprofile=coverage.txt -covermode=atomic \
            ./...
      - uses: codecov/codecov-action@v3
        if: always()
